[package]
name = "df_texture_helper"
version = "0.1.0"
edition = "2021"
authors = ["Barely_Creative"]
description = "A tool to make defining Dwarf Fortress Premium graphics easier"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
convert_case = "0.6.0"
eframe = "0.27.2"
egui = "0.27.2"
egui_plot = "0.27.2"
egui_extras = { version = "0.27.2", default-features = false, features = ["image"] }
image = { version = "0.25.1", default-features = false, features = ["png"] }
rfd = "0.14.1"
thiserror = "1.0.40"
