[package]
name = "df_texture_helper"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
convert_case = "0.6.0"
eframe = "0.21.3"
egui = "0.21.0"
image = { version = "0.24.6", default-features = false, features = ["png"] }
rfd = "0.11.3"
